services:
  app:
    build: .
    container_name: empacotador-api
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - JWT_SECRET=49c63cb8bebdee10752a1224f1802afe
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/docs']
      interval: 30s
      timeout: 10s
      retries: 3
